name: Kotlin CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build test
